// Generated by CoffeeScript 2.2.1
var hello;

import {
  send
} from 'micro';

import {
  router,
  get
} from 'microrouter';

hello = async(req, res) => {
  return send(res, 200, (await Promise.resolve(`Hello ${req.params.who}`)));
};

export default router(get('/hello/:who', hello));
